title : Faqih Abdul Karim
logo: /Faqih(E)/foto/faqih.jpg
description: Versatile individual with experience collecting, transforming, and organizing data for analysis to help make informed
decisions. Excellent understanding and proficiency of platform for effective data analyses, including SQL, spreadsheet,
Tableau, and R. Strong communication, organizational, and analytical skills. Recently completed the Google data Analytics
Certificate -a rigorous, hands-on program that covers the entire scope of the data analysis process.
show_downloads: true
theme: jekyll-theme-minimal
